apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kafka.strimzi.io/v1beta2","kind":"KafkaConnector","metadata":{"annotations":{},"labels":{"strimzi.io/cluster":"cms-oracle-source"},"name":"cms-oracle-source-po-item-kfm","namespace":"kafka"},"spec":{"class":"io.debezium.connector.oracle.OracleConnector","config":{"database.dbname":"${secrets:kafka/cms-oracle-credentials:databaseDbname}","database.hostname":"${secrets:kafka/cms-oracle-credentials:databaseHostname}","database.password":"${secrets:kafka/cms-oracle-credentials:databasePassword}","database.pdb.name":"pdbptuat","database.port":"${secrets:kafka/cms-oracle-credentials:databasePort}","database.server.name":"cms.oracle","database.user":"${secrets:kafka/cms-oracle-credentials:databaseUser}","decimal.handling.mode":"string","errors.log.enable":true,"errors.log.include.messages":true,"errors.tolerance":"all","include.schema.changes":"true","key.converter":"org.apache.kafka.connect.storage.StringConverter","key.converter.schemas.enable":false,"schema.history.internal.consumer.sasl.jaas.config":"org.apache.kafka.common.security.scram.ScramLoginModule required username=\"cms-oracle-kafkaconnect\" password=\"zFU26WDhLjJy\";","schema.history.internal.consumer.sasl.mechanism":"SCRAM-SHA-512","schema.history.internal.consumer.security.protocol":"SASL_PLAINTEXT","schema.history.internal.kafka.bootstrap.servers":"onelife-kafka-bootstrap.kafka.svc.cluster.local:9092","schema.history.internal.kafka.topic":"schema-changes.cms_oracle","schema.history.internal.producer.sasl.jaas.config":"org.apache.kafka.common.security.scram.ScramLoginModule required username=\"cms-oracle-kafkaconnect\" password=\"zFU26WDhLjJy\";","schema.history.internal.producer.sasl.mechanism":"SCRAM-SHA-512","schema.history.internal.producer.security.protocol":"SASL_PLAINTEXT","schema.history.internal.store.only.captured.tables.ddl":true,"snapshot.mode":"initial","table.include.list":"SRSYS.CM_PO_ITEM_KFM","time.precision.mode":"connect","tombstones.on.delete":false,"topic.prefix":"cms.cdc","transforms":"unwrap,filterSchemaRecord,reroute,dropRerouteKey,insertKey,extractStrKey","transforms.dropRerouteKey.type":"io.confluent.connect.transforms.Drop$Key","transforms.extractStrKey.field":"ID","transforms.extractStrKey.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.filterSchemaRecord.condition":"value.tableChanges == null","transforms.filterSchemaRecord.language":"jsr223.graal.js","transforms.filterSchemaRecord.type":"io.debezium.transforms.Filter","transforms.insertKey.fields":"ID","transforms.insertKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.reroute.topic.regex":"(.*)","transforms.reroute.topic.replacement":"cms.cm_po_item_kfm","transforms.reroute.type":"io.debezium.transforms.ByLogicalTableRouter","transforms.unwrap.delete.handling.mode":"drop","transforms.unwrap.drop.tombstones":true,"transforms.unwrap.type":"io.debezium.transforms.ExtractNewRecordState","value.converter":"org.apache.kafka.connect.json.JsonConverter","value.converter.schemas.enable":false},"tasksMax":1}}
  creationTimestamp: "2023-03-08T04:00:39Z"
  generation: 2
  labels:
    strimzi.io/cluster: cms-oracle-source
  name: cms-oracle-source-po-item-kfm
  namespace: kafka
  resourceVersion: "325268713"
  uid: 36462044-e64f-4df5-91e1-c79b2e28b82f
spec:
  class: io.debezium.connector.oracle.OracleConnector
  config:
    database.dbname: ${secrets:kafka/cms-oracle-credentials:databaseDbname}
    database.hostname: ${secrets:kafka/cms-oracle-credentials:databaseHostname}
    database.password: ${secrets:kafka/cms-oracle-credentials:databasePassword}
    database.pdb.name: pdbptuat
    database.port: ${secrets:kafka/cms-oracle-credentials:databasePort}
    database.server.name: cms.oracle
    database.user: ${secrets:kafka/cms-oracle-credentials:databaseUser}
    decimal.handling.mode: string
    errors.log.enable: true
    errors.log.include.messages: true
    errors.tolerance: all
    include.schema.changes: "true"
    key.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable: false
    schema.history.internal.consumer.sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule
      required username="cms-oracle-kafkaconnect" password="zFU26WDhLjJy";
    schema.history.internal.consumer.sasl.mechanism: SCRAM-SHA-512
    schema.history.internal.consumer.security.protocol: SASL_PLAINTEXT
    schema.history.internal.kafka.bootstrap.servers: onelife-kafka-bootstrap.kafka.svc.cluster.local:9092
    schema.history.internal.kafka.topic: schema-changes.cms_oracle
    schema.history.internal.producer.sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule
      required username="cms-oracle-kafkaconnect" password="zFU26WDhLjJy";
    schema.history.internal.producer.sasl.mechanism: SCRAM-SHA-512
    schema.history.internal.producer.security.protocol: SASL_PLAINTEXT
    schema.history.internal.store.only.captured.tables.ddl: true
    snapshot.mode: initial
    table.include.list: SRSYS.CM_PO_ITEM_KFM
    time.precision.mode: connect
    tombstones.on.delete: false
    topic.prefix: cms.cdc
    transforms: unwrap,filterSchemaRecord,reroute,dropRerouteKey,insertKey,extractStrKey
    transforms.dropRerouteKey.type: io.confluent.connect.transforms.Drop$Key
    transforms.extractStrKey.field: ID
    transforms.extractStrKey.type: org.apache.kafka.connect.transforms.ExtractField$Key
    transforms.filterSchemaRecord.condition: value.tableChanges == null
    transforms.filterSchemaRecord.language: jsr223.graal.js
    transforms.filterSchemaRecord.type: io.debezium.transforms.Filter
    transforms.insertKey.fields: ID
    transforms.insertKey.type: org.apache.kafka.connect.transforms.ValueToKey
    transforms.reroute.topic.regex: (.*)
    transforms.reroute.topic.replacement: cms.cm_po_item_kfm
    transforms.reroute.type: io.debezium.transforms.ByLogicalTableRouter
    transforms.unwrap.delete.handling.mode: drop
    transforms.unwrap.drop.tombstones: true
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
  tasksMax: 1
status:
  conditions:
  - lastTransitionTime: "2023-09-15T06:11:29.044216Z"
    status: "True"
    type: Ready
  connectorStatus:
    connector:
      state: RUNNING
      worker_id: 10.42.188.112:8083
    name: cms-oracle-source-po-item-kfm
    tasks:
    - id: 0
      state: FAILED
      trace: "org.apache.kafka.connect.errors.ConnectException: An exception occurred
        in the change event producer. This connector will be stopped.\n\tat io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:53)\n\tat
        io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:225)\n\tat
        io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:59)\n\tat
        io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:174)\n\tat
        io.debezium.pipeline.ChangeEventSourceCoordinator.executeChangeEventSources(ChangeEventSourceCoordinator.java:141)\n\tat
        io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)\n\tat
        java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat
        java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat
        java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat
        java.base/java.lang.Thread.run(Thread.java:829)\nCaused by: java.sql.SQLException:
        ORA-01653: unable to extend table SYS.LOGMNRLT_99373_COL$ by 128 in tablespace
        SYSAUX\nORA-06512: at \"SYS.DBMS_LOGMNR\", line 72\nORA-06512: at line 1\n\n\tat
        oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:630)\n\tat oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:564)\n\tat
        oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1151)\n\tat oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:771)\n\tat
        oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:299)\n\tat oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:498)\n\tat
        oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:112)\n\tat oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:1011)\n\tat
        oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:1531)\n\tat
        oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1311)\n\tat
        oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:2163)\n\tat
        oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:2118)\n\tat
        oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:328)\n\tat
        io.debezium.jdbc.JdbcConnection.executeWithoutCommitting(JdbcConnection.java:1440)\n\tat
        io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.startMiningSession(LogMinerStreamingChangeEventSource.java:581)\n\tat
        io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:207)\n\t...
        9 more\nCaused by: Error : 1653, Position : 0, Sql = BEGIN sys.dbms_logmnr.start_logmnr(startScn
        => '6011972542425', endScn => '6011972543744', OPTIONS => DBMS_LOGMNR.DICT_FROM_REDO_LOGS
        + DBMS_LOGMNR.DDL_DICT_TRACKING  + DBMS_LOGMNR.NO_ROWID_IN_STMT);END;, OriginalSql
        = BEGIN sys.dbms_logmnr.start_logmnr(startScn => '6011972542425', endScn =>
        '6011972543744', OPTIONS => DBMS_LOGMNR.DICT_FROM_REDO_LOGS + DBMS_LOGMNR.DDL_DICT_TRACKING
        \ + DBMS_LOGMNR.NO_ROWID_IN_STMT);END;, Error Msg = ORA-01653: unable to extend
        table SYS.LOGMNRLT_99373_COL$ by 128 in tablespace SYSAUX\nORA-06512: at \"SYS.DBMS_LOGMNR\",
        line 72\nORA-06512: at line 1\n\n\tat oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:637)\n\t...
        24 more\n"
      worker_id: 10.42.188.112:8083
    type: source
  observedGeneration: 2
  tasksMax: 1
  topics: []
