apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 11
  labels:
    app.kubernetes.io/instance: kowl
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: console
    app.kubernetes.io/version: v2.2.0
    helm.sh/chart: console-0.5.6
  name: kowl-console
  namespace: kafka
  resourceVersion: "332844775"
  uid: b4ed3074-bfcd-4dd3-848e-998c5e0e698d
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: kowl
      app.kubernetes.io/name: console
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - args:
        - --config.filepath=/etc/console/configs/config.yaml
        env:
        - name: KAFKA_SASL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: kafka-sasl-password
              name: kowl-console
        - name: LOGIN_JWTSECRET
          valueFrom:
            secretKeyRef:
              key: login-jwt-secret
              name: kowl-console
        image: vectorized/console:v2.2.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /admin/health
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: console
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /admin/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/console/configs
          name: configs
          readOnly: true
        - mountPath: /etc/console/secrets
          name: secrets
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 99
        runAsUser: 99
      serviceAccount: kowl-console
      serviceAccountName: kowl-console
      terminationGracePeriodSeconds: 30
      volumes: {}
