apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    field.cattle.io/publicEndpoints: '[{"addresses":["103.245.249.219"],"port":443,"protocol":"HTTPS","serviceName":"kafka:kowl-console","ingressName":"kafka:kowl-console","hostname":"kowl.staging.onelife.ficus.ai","path":"/","allNodes":false}]'
    meta.helm.sh/release-name: kowl
    meta.helm.sh/release-namespace: kafka
  creationTimestamp: "2023-01-10T14:14:21Z"
  generation: 11
  labels:
    app.kubernetes.io/instance: kowl
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: console
    app.kubernetes.io/version: v2.2.0
    helm.sh/chart: console-0.5.6
  name: kowl-console
  namespace: kafka
  resourceVersion: "332844775"
  uid: b4ed3074-bfcd-4dd3-848e-998c5e0e698d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: kowl
      app.kubernetes.io/name: console
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-04-10T11:21:59+07:00"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kowl
        app.kubernetes.io/name: console
    spec:
      containers:
      - args:
        - --config.filepath=/etc/console/configs/config.yaml
        env:
        - name: KAFKA_SASL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: kafka-sasl-password
              name: kowl-console
        - name: LOGIN_JWTSECRET
          valueFrom:
            secretKeyRef:
              key: login-jwt-secret
              name: kowl-console
        image: vectorized/console:v2.2.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /admin/health
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: console
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /admin/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/console/configs
          name: configs
          readOnly: true
        - mountPath: /etc/console/secrets
          name: secrets
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 99
        runAsUser: 99
      serviceAccount: kowl-console
      serviceAccountName: kowl-console
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: kowl-console
        name: configs
      - name: secrets
        secret:
          defaultMode: 420
          secretName: kowl-console
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-01-10T14:14:21Z"
    lastUpdateTime: "2023-04-10T04:22:20Z"
    message: ReplicaSet "kowl-console-7455b9cd88" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-09-27T15:52:33Z"
    lastUpdateTime: "2023-09-27T15:52:33Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 11
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
